name: Build and push
on:
  workflow_call:
    inputs:
      name:
        description: 'Name'
        default: "John Doe"
        required: false
        type: string
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo 'Hello Mr. ${{ inputs.name }}'
        ls -al
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      with:
        script: |
          const script = require('./path/to/script.js')
          console.log(script({github, context}))