name: Build and push
on:
  workflow_call:
    inputs:
      name:
        description: 'Name'
        default: "John Doe"
        required: false
        type: string
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo 'Hello Mr. ${{ inputs.name }}'
        ls -al
    - name: Checkout shared repo
      uses: actions/checkout@v3
      with:
        repository: samit-maersk/github-shared-pipeline
        path: tools
    - run: |
        ls -al
        ls -al tools
    - uses: actions/github-script@v6
      with:
        script: |
          const script = require('./tools/.github/workflows/cluster.js')
          console.log(script({github, context}))