name: Deploy

on:
  workflow_call:
    inputs:
      deployTo:
        description: 'env to deploy'
        default: "dev"
        required: true
        type: string
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Deployment to ${{ inputs.deployTo }}'