name: Pipeline

on:
  workflow_call:
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      name: "Samit"
  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      deployTo: "dev"